networks:
  pong-network:
    driver: bridge

services:
  backend:
    build: ./backend
    networks:
      - pong-network
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env  # Load environment variables from file
    volumes:
      - ./backend:/app
      - ./tls:/app/tls
      - /app/node_modules
    environment:
      - TLS_PATH=/app/tls
      - NODE_TLS_REJECT_UNAUTHORIZED=0  # Allow self-signed certificates for development

  frontend:
    build: ./frontend
    networks:
      - pong-network
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env  # Load environment variables from file
    volumes:
      - ./frontend:/app
      - ./tls:/app/tls
      - /app/node_modules
    environment:
      - TLS_PATH=/app/tls
      - NODE_TLS_REJECT_UNAUTHORIZED=0  # Allow self-signed certificates for development
    command: npm run dev
    depends_on:
      - backend

  ngrok:
    build: ./ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=31n4ws6BtctGyeqtvgsJqCfNf6U_53Wz1pUyFLNJaHED1HYaL
      - VITE_PORT=5173
      - VITE_HOST=https://frontend
    depends_on:
      - frontend
      - backend
    ports:
      - "4040:4040"
    networks:
      - pong-network
